language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

notifications:
 email:
   on_success: always
   on_failure: always
 slack: cgiwave6:h9BQb1Y4KA4QNTysVx79hgt0
install:
  - npm install -g yarn
script:
  - npm install -g @angular/cli
  - npm run lint
  - npm run test
  - npm run build --base-href https://harsha110.github.io/angularTestting/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angularTestting
  on:
    branch: master