sudo: required

language: node_js
node_js:
  - "10.9.0"
dist: trusty



branches:
  only:
  - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: always
    on_failure: always
  slack: cgiwave6:h9BQb1Y4KA4QNTysVx79hgt0
  
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
   
before_script:
 - npm install -g @angular-devkit/build-angular
 - npm install -g @angular/cli
 - npm install

script:
 - ng build
 - ng test --watch=false


build:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angularTestting  
  on:
    branch: master

after_sucess:
  - /bin/bash ./deploy.sh    