language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

notifications:
 email:
   on_success: always
   on_failure: always
 slack: cgiwave6:h9BQb1Y4KA4QNTysVx79hgt0
install:
  - npm install -g yarn
before_script:
 - npm install -g @angular-devkit/build-angular
 - npm install -g @angular/cli

script:
 -ng build
 -ng test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angularTestting
  on:
    branch: master